export const buildings = `arch.svg
arch_outline.svg
batchsvgtopng
blacksmith.svg
blacksmith_outline.svg
bridge_stone1.svg
bridge_stone1_outline.svg
bridge_stone2.svg
bridge_stone2_outline.svg
bridge_wood.svg
bridge_wood_outline.svg
buildings.txt
caravan.svg
caravan_outline.svg
caravan_wreck.svg
caravan_wreck_outline.svg
castle1.svg
cathedral.svg
cathedral_outline.svg
cave_entrance.svg
cave_entrance_outline.svg
circus.svg
circus_outline.svg
city.svg
city_outline.svg
docks.svg
docks_outline.svg
farm.svg
farm_outline.svg
fishery.svg
fishery_outline.svg
fort.svg
fortress.svg
fortress_outline.svg
fort_outline.svg
fountain.svg
fountain_outline.svg
gallows.svg
gallows_outline.svg
gate.svg
gate_outline.svg
graveyard.svg
graveyard_outline.svg
hill1.svg
hill2.svg
hill3.svg
hill4.svg
hill5.svg
hill6.svg
hill7.svg
hunter.svg
hunter_outline.svg
inn.svg
inn_outline.svg
jailhouse.svg
jailhouse_outline.svg
magic_stones.svg
magic_stones_outline.svg
marsh.svg.png
maze.svg
maze_outline.svg
mine.svg
mine_outline.svg
monastery.svg
monastery_outline.svg
mountain1.svg
mountain2.svg
mountain3.svg
mountain4.svg
mountain5.svg
mountain6.svg
mountain7.svg
obelisk.svg
obelisk_outline.svg
plant01.svg
plant02.svg
pond.svg
pond_outline.svg
pyramid.svg
pyramid_outline.svg
ruins.svg
ruins_outline.svg
shipwreck.svg
shipwreck_outline.svg
sign_crossroad.svg
sign_crossroad_outline.svg
sign_left.svg
sign_left_outline.svg
sign_post.svg
sign_post_outline.svg
stables.svg
stables_outline.svg
statue.svg
statue_outline.svg
sword_in_the_stone.svg
sword_in_the_stone_outline.svg
tavern.svg
tavern_outline.svg
tent.svg
tent_outline.svg
totem.svg
totem_outline.svg
tower_flag_red.svg
tower_round.svg
tower_round_flag.svg
tower_round_flag_outline.svg
tower_round_outline.svg
tower_square.svg
tower_square_outline.svg
townhall.svg
townhall_outline.svg
tree01.svg
tree02.svg
tree03.svg
tree04.svg
tree05.svg
tree06.svg
tree07.svg
tree08.svg
tree09.svg
tree10.svg
tree11.svg
tree12.svg
tree13.svg
tree14.svg
tree15.svg
university.svg
university_outline.svg
village.svg
village_outline.svg
warehouse.svg
warehouse_outline.svg
watch_tower.svg
watch_tower_outline.svg
windmill.svg
windmill_outline.svg
wishing_well.svg
wishing_well_outline.svg
`.split('\n');